val carMakes = listOf(
    "Toyota", "Honda", "Ford", "BMW", "Nissan", "Chevrolet", "Volkswagen",
    "Hyundai", "Kia", "Subaru", "Mazda", "Porsche", "Audi", "Lexus",
    "Dodge", "Chrysler", "Buick", "GMC", "Jaguar", "Land Rover",
    "Mercedes-Benz", "Tesla", "Volvo", "Infiniti", "Acura", "Mitsubishi",
    "Fiat", "Alfa Romeo", "Peugeot", "Renault", "Citroën",
    "Tata Motors", "Jeep", "Lincoln", "Mini", "Bentley",
    "Rolls-Royce", "McLaren", "Lamborghini", "Ferrari", "Aston Martin"
)

val carModels = mapOf(
    "Toyota" to listOf("Camry", "Corolla", "RAV4", "Prius", "Highlander", "Tacoma", "Tundra", "Sienna", "Avalon", "C-HR"),
    "Honda" to listOf("Civic", "Accord", "CR-V", "Fit", "Pilot", "HR-V", "Ridgeline", "Insight", "Clarity", "Passport"),
    "Ford" to listOf("Focus", "Mustang", "Explorer", "F-150", "Escape", "Fusion", "Edge", "Ranger", "Bronco", "Maverick"),
    "BMW" to listOf("X3", "X5", "3 Series", "5 Series", "7 Series", "Z4", "i3", "i4", "iX", "M4"),
    "Nissan" to listOf("Altima", "Sentra", "Maxima", "Rogue", "Murano", "Pathfinder", "Armada", "Juke", "370Z", "Leaf"),
    "Chevrolet" to listOf("Silverado", "Malibu", "Equinox", "Traverse", "Tahoe", "Suburban", "Blazer", "Spark", "Camaro", "Corvette"),
    "Volkswagen" to listOf("Golf", "Jetta", "Passat", "Tiguan", "Atlas", "Beetle", "Arteon", "ID.4", "Phaeton", "T-Roc"),
    "Hyundai" to listOf("Elantra", "Sonata", "Tucson", "Santa Fe", "Kona", "Ioniq", "Veloster", "Palisade", "Santa Cruz", "Azera"),
    "Kia" to listOf("Seltos", "Sorento", "Sportage", "Optima", "Forte", "Cadenza", "K5", "Telluride", "Niro", "Rio"),
    "Subaru" to listOf("Outback", "Forester", "Crosstrek", "Ascent", "Impreza", "Legacy", "WRX", "BRZ", "Baja", "Alcyone"),
    "Mazda" to listOf("Mazda3", "Mazda6", "CX-3", "CX-30", "CX-5", "CX-9", "MX-5 Miata", "Mazda2", "Mazda5", "Tribute"),
    "Porsche" to listOf("911", "Cayenne", "Macan", "Boxster", "Cayman", "Panamera", "Taycan", "918 Spyder", "964", "996"),
    "Audi" to listOf("A3", "A4", "A6", "A8", "Q3", "Q5", "Q7", "Q8", "TT", "R8"),
    "Lexus" to listOf("ES", "IS", "GS", "LS", "NX", "RX", "GX", "LX", "LC", "UX"),
    "Dodge" to listOf("Charger", "Challenger", "Durango", "Journey", "Grand Caravan", "Dakota", "Viper", "Neon", "Caliber", "Intrepid"),
    "Chrysler" to listOf("300", "Pacifica", "Voyager", "Aspen", "Sebring", "Saratoga", "Imperial", "New Yorker", "PT Cruiser", "Concorde"),
    "Buick" to listOf("Regal", "Enclave", "Encore", "LaCrosse", "Verano", "Century", "Rendezvous"),
        "GMC" to listOf("Sierra", "Yukon", "Terrain", "Acadia", "Canyon", "Savana", "Envoy", "Jimmy", "Sonoma", "TerrainDenali"),
        "Jaguar" to listOf("XF", "XE", "F-PACE", "E-PACE", "F-TYPE", "XJ", "I-PACE", "XK", "S-Type", "X-Type"),
        "Land Rover" to listOf("Defender", "Range Rover", "Discovery", "Evoque", "Sport", "Velar", "LR2", "LR4", "Freelander", "Series I"),
        "Mercedes-Benz" to listOf("C-Class", "E-Class", "S-Class", "GLE", "GLC", "GLS", "A-Class", "CLA", "G-Class", "EQC"),
        "Tesla" to listOf("Model S", "Model 3", "Model X", "Model Y", "Roadster", "Cybertruck", "Model 2", "Model X Plaid", "Model S Plaid", "Model 3 Performance"),
        "Volvo" to listOf("S60", "S90", "V60", "V90", "XC40", "XC60", "XC90", "V40", "S40", "C30"),
        "Infiniti" to listOf("Q50", "Q60", "Q70", "QX50", "QX60", "QX80", "G35", "G37", "M35", "M37"),
        "Acura" to listOf("TLX", "ILX", "RDX", "MDX", "ZDX", "RSX", "SLX", "Legend", "Integra", "Vigor"),
        "Mitsubishi" to listOf("Outlander", "Eclipse Cross", "RVR", "Lancer", "Galant", "Mirage", "Montero", "Eclipse", "Demon", "i-MiEV"),
        "Fiat" to listOf("500", "Panda", "Tipo", "500L", "500X", "Ducato", "Stilo", "Bravo", "Barchetta", "Linea"),
        "Alfa Romeo" to listOf("Giulia", "Stelvio", "4C", "Milano", "147", "156", "159", "Mito", "Giulietta", "GTV"),
        "Peugeot" to listOf("308", "3008", "5008", "208", "2008", "508", "Partner", "Expert", "Traveller", "Bipper"),
        "Renault" to listOf("Clio", "Megane", "Captur", "Kadjar", "Talisman", "Koleos", "Scenic", "Espace", "Zoe", "Trafic"),
        "Citroën" to listOf("C3", "C4", "C5", "Cactus", "Berlingo", "DS3", "DS4", "DS5", "C-Elysée", "Jumpy"),
        "Tata Motors" to listOf("Nexon", "Harrier", "Safari", "Tiago", "Tigor", "Hexa", "Zest", "Punch", "Altroz", "Nano"),
        "Jeep" to listOf("Wrangler", "Cherokee", "Grand Cherokee", "Renegade", "Compass", "Gladiator", "Liberty", "Commander", "Patriot", "Wagoneer"),
        "Lincoln" to listOf("Navigator", "Aviator", "MKZ", "MKT", "Corsair", "Continental", "MKX", "Zephyr", "MKS", "Town Car"),
        "Mini" to listOf("Cooper", "Countryman", "Clubman", "Paceman", "Roadster", "Convertible", "John Cooper Works", "Mini Electric", "Mini Coupe", "Mini Hatch"),
        "Bentley" to listOf("Continental GT", "Bentayga", "Flying Spur", "Mulsanne", "Arnage", "Brooklands", "Azure", "EXP 10 Speed 6", "Bentley Speed 8", "Bentley Speed 12"),
        "Rolls-Royce" to listOf("Phantom", "Ghost", "Wraith", "Dawn", "Cullinan", "Silver Spirit", "Silver Shadow", "Corniche", "Park Ward", "Aero Cowling"),
        "McLaren" to listOf("720S", "570S", "600LT", "Artura", "P1", "Elva", "675LT", "MP4-12C", "765LT", "McLaren GT"),
        "Lamborghini" to listOf("Huracán", "Aventador", "Urus", "Gallardo", "Espy", "Sian", "Centenario", "Veneno", "Murciélago", "Reventón"),
        "Ferrari" to listOf("488 GTB", "F8 Tributo", "Roma", "Portofino", "LaFerrari", "California T", "812 Superfast", "SF90 Stradale", "F12 Berlinetta", "Maranello"),
        "Aston Martin" to listOf("DB11", "Vantage", "DBS Superleggera", "Rapide", "DB9", "Virage", "Vulcan", "Lagonda", "One-77", "Cygnet")
    )


